language: python
sudo: false
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

os:
- linux

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install numpy scipy pyopengl pytest flake8 six coverage bokeh pyqtgraph matplotlib pandas --yes
  - conda install pyqt --yes
  - pip install cdflib
  - pip install -e .[tests]

before_script:
  # We need to create a (fake) display on Travis, let's use a funny resolution
  - export DISPLAY=:99.0
  - "sh -e /etc/init.d/xvfb start"
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
  #Run pytest
  - ls
  - pytest -rsv

after_success:
  #Send the results to coveralls
  - pytest --cov --cov-config=setup.cfg;
  - coveralls;
