language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

os:
- linux

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda install numpy scipy pyopengl pytest flake8 six coverage bokeh pyqtgraph matplotlib pandas --yes
  - conda install pyqt --yes
  - pip3.7 install cdflib
script:
- pytest -rsv
#- flake8
# - mypy . --ignore-missing-imports

after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.7* ]]; then
  pytest --cov --cov-config=setup.cfg;
  coveralls;
  fi