name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        chmod +x miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        sudo apt-get update
        sudo apt-get -y install libgl1-mesa-glx
        conda install xarray numpy scipy pyopengl pytest flake8 six coverage bokeh pyqtgraph matplotlib --yes
        conda install pyqt --yes
        conda install -c anaconda netcdf4 --yes
        conda install -c mavensdc cdflib --yes
        ls 
        cd $HOME/miniconda/bin
        ls
        cd ../../
    - name: set up XVFB
      uses: GabrielBB/xvfb-action@v1.0
      with:
        run: $HOME/miniconda/bin/pytest -rsv